### ISSUE TITLE
Create Habits and Plans

### ISSUE THREAD

**Issue by leroynle** [cs130-w21/7#12]
## User Story
As a potential user, I would like to have the functionality of creating my eating habits and plans so that I can search for recommendations in one click.

## Acceptance Criteria
- [x] create a form for eating habits.
- [x] create a form for eating plans.

**Comment by ngducn** [comment]
The UI for creating eating preferences, habits and plan took longer than I expected. I will move this from Sprint 1 to Sprint 2 to ensure the quality of my code.
